### ISSUE TITLE
Alipay.podspec version issues

### ISSUE THREAD

**Issue by devluyy** [beiliubei/AliPay#2]
pod search Alipay
-> AliPay (2.1.2)
   支付宝 sdk
   pod 'AliPay', '~> 2.1.2'
- Homepage: https://b.alipay.com/newIndex.htm
- Source:   https://github.com/beiliubei/AliPay.git
- Versions: 2.1.2 [master repo]
  this versioin is not 2.1.2.1,

**Comment by beiliubei** [comment]
2.1.2.1 和 2.1.2是相同的内容， 文件内容没有做更改，只是把openssl的文件目录地址调整了一下
